### ISSUE TITLE
'module' object has no attribute 'OpenStackConfigException'

### ISSUE THREAD

**Issue by alissonpmedeiros** [OpenStackCookbook/vagrant-openstack#26]
In **Demo Script sections** I tried execute `/vagrant/lab_environment_setup.sh` and I got and error **'module' object has no attribute 'OpenStackConfigException'**

I'm new in Openstack, so after installing all requirements Horizon interface not working in address https://192.168.100.10/

**Comment by uksysadmin** [comment]
Apologies for the delay. I missed the notification whilst away. Can you let me know what steps you took to get here? (I'm assuming the basics of what was described, but just checking if anything else was added/amended). Also would be helpful to know:
Operating System
VirtualBox or VMware versions you're using
Vagrant version

I'm currently spinning this up to see if I can recreate. I find that these errors are usually transient/temporary in that at some point during the installation, something didn't get installed -and Ansible didn't completely bomb out on an error.

Thanks,
Kev

**Comment by uksysadmin** [comment]
I've just spun up a new environment and can't recreate the error. Can you paste the whole output so I can see at what point it is erroring?
